image: gradle:latest

Build project:
  stage: build
  script:
    - gradle assemble

Test project:
  stage: test
  script:
    - gradle test
  artifacts:
    paths:
      - build/test-results/test/TEST-*.xml
    reports:
      junit: build/test-results/test/TEST-*.xml
