image: gradle:latest

variables:
   MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
   paths:
      - .m2/repository

Build project:
   stage: build
   script:
      - gradle $MAVEN_OPTS classes

Test project:
   stage: test
   script:
      - gradle $MAVEN_OPTS test
   artifacts:
      paths:
         - build/test-results/test/TEST-*.xml
      reports:
         junit: build/test-results/test/TEST-*.xml

Package artifact:
   image: bellsoft/liberica-openjdk-alpine:15
   stage: deploy
   script:
      - ./gradlew $MAVEN_OPTS assemble
   artifacts:
      paths:
         - build/libs/team-city-monitor-*-SNAPSHOT.jar
      expire_in: 30 days
