teamcity:
  host: teamcity.example.com
  login: U.Ser
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github-client-id
            clientSecret: github-client-secret
