name: Java CI with Gradle and DockerHub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Login to Docker Hub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.1.1
      id: buildx
    - name: Build and push Docker image   
      uses: docker/build-push-action@v2.3.0
      with: 
        context: ./
        file: ./Dockerfile
        push: true
        tags: pgavrilenko/team-city-monitor
      id: docker_build
    - name: Image digest  
      run: echo ${{ steps.docker_build.outputs.digest }}
