name: Java CI\CD with Gradle, DockerHub and Azure WebApps

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    tags:
     - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Login to Docker Hub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.1.1
      id: buildx

    - name: Build and push Docker image   
      uses: docker/build-push-action@v2.3.0
      with: 
        context: ./
        file: ./Dockerfile
        push: true
        tags: 'pgavrilenko/team-city-monitor:gh-${{ github.sha }}'
      id: docker_build

    - name: Image digest  
      run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'team-city-monitor'
        images: 'pgavrilenko/team-city-monitor:gh-${{ github.sha }}'
